### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by stugol** [t9md/atom-project-folder#2]
[Enter steps to reproduce below:]
1. Hit space when there are no projects to remove

**Atom Version**: 1.7.1
**System**: Mac OS X 10.10.5
**Thrown From**: [project-folder](https://github.com/t9md/atom-project-folder) package, v0.1.8
### Stack Trace

Uncaught TypeError: Path must be a string. Received null

```
At path.js:8

TypeError: Path must be a string. Received null
    at assertPath (path.js:8:11)
    at Object.posix.normalize (path.js:450:3)
    at Project.module.exports.Project.removePath (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:270:28)
    at View.remove (/Users/infinity/.atom/packages/project-folder/lib/view.coffee:145:18)
    at View.confirmAndContinue (/Users/infinity/.atom/packages/project-folder/lib/view.coffee:111:5)
    at space-pen-div.atom.commands.add.project-folder:confirm-and-continue (/Users/infinity/.atom/packages/project-folder/lib/view.coffee:44:50)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:23.3.0 core:copy (atom-text-editor#project-folder.projectRootDirectories.editor.mini.is-focused)
     -0:23.1.0 core:move-right (atom-text-editor#project-folder.projectRootDirectories.editor.mini.is-focused)
  2x -0:22.1.0 core:paste (atom-text-editor#project-folder.projectRootDirectories.editor.mini.is-focused)
  6x -0:18.2.0 core:backspace (atom-text-editor#project-folder.projectRootDirectories.editor.mini.is-focused)
     -0:14.5.0 core:paste (atom-text-editor#project-folder.projectRootDirectories.editor.mini.is-focused)
     -0:13 editor:move-to-end-of-line (atom-text-editor#project-folder.projectRootDirectories.editor.mini.is-focused)
     -0:12.3.0 core:backspace (atom-text-editor#project-folder.projectRootDirectories.editor.mini.is-focused)
     -0:10.5.0 core:confirm (atom-text-editor#project-folder.projectRootDirectories.editor.mini.is-focused)
     -0:08.5.0 core:close (atom-text-editor#project-folder.projectRootDirectories.editor.mini.is-focused)
     -0:07.0 project-folder:add (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:06.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:06.0 tree-view:toggle-focus (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:05.5.0 project-folder:add (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:04.6.0 project-folder:switch-action (atom-text-editor.editor.mini.is-focused)
  6x -0:03.6.0 project-folder:confirm-and-continue (atom-text-editor.editor.mini.is-focused)
     -0:01.0 project-folder:switch-action (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-ruby",
      "spell-check",
      "wrap-guide",
      "wrap-guide",
      "deprecation-cop",
      "symbols-view",
      "define-jump",
      "goto",
      "haxe",
      "nuclide-click-to-symbol",
      "nuclide-find-references",
      "one-tab",
      "atom-ctags",
      "linter-crystal",
      "linter-ruby",
      "atom-slime",
      "ruby-navigator",
      "language-ruby-on-rails",
      "snippets",
      "text-pastry",
      "tab-switcher",
      "fun-files",
      "SFTP-deployment",
      "line-ending-converter",
      "project-plus"
    ],
    "ignoredNames": [
      ".*",
      "flxg_stats.txt"
    ],
    "packagesWithKeymapsDisabled": []
  },
  "project-folder": {
    "hideLoadedFolderFromAddList": false,
    "projectRootDirectories": [
      "/Volumes/nas-data/Documents/Programming/",
      "/Volumes/nas-data/Documents/Programming/ruby",
      "/Volumes/nas-data/Documents/Programming/shell-scripts",
      "/Volumes/nas-data/Documents/Programming/c  ",
      "~/programming"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Parinfer, v1.14.0
Stylus, v3.0.0
arpeggio, v1.1.2
atom-dlang, v1.1.2
autocomplete-ruby, v0.1.0
build, vundefined
cargo-test-runner, v0.0.5
color-picker, v2.1.1
fold-functions, v0.4.3
indent-guide-improved, v1.4.5
language-crystal-actual, v0.28.2
language-dylan, v0.7.3
language-felix, v0.0.2
language-haml, v0.24.0
language-haxe, v0.4.3
language-lisp, v0.2.0
language-livescript, v0.0.2
language-onyx, v0.1.0
language-ruby-without-erb, v0.60.0
language-rust, v0.4.6
linter, v1.11.4
linter-rust, v0.4.5
minimap, v4.21.0
multi-wrap-guide, v0.23.5
navigation-history, v0.1.8
pigments, v0.26.0
project-folder, v0.1.8
project-viewer, v0.2.31
racer, v0.20.0
regex-railroad-diagram, v0.16.0
remote-sync, v4.0.1
ruby-block, v0.3.5
rust-api-docs-helper, v0.5.1
simple-drag-drop-text, v0.3.0
tabasco, v0.4.0
terminal-plus, v0.14.5
toggle-gutter, v0.2.2
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by t9md** [comment]
Thanks for catching this!
